background              #1E1F1D
foreground              #E6E8E5
cursor                  #7E8F83
selection_background    #4A5A4F

# Normal Colors
color0  #1E1F1D
color1  #B86A64
color2  #7AA487
color3  #C2AA72
color4  #7B8B90
color5  #8F7A76
color6  #5F7064
color7  #E6E8E5

# Bright Colors
color8  #3D403E
color9  #BF7A74
color10 #88B693
color11 #D3BB85
color12 #8BA0A6
color13 #9B8983
color14 #7E8F83
color15 #F2F3F1
